name: collision_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0=py_1
  - altair_saver
  - ipykernel==6.5.0
  - pandas==1.3.4
  - pip=21.3.1=pyhd8ed1ab_0
  - python=3.10.0
  - scikit-learn==1.0.1
  - pip:
    - altair-data-server==0.4.1
    - altair-viewer==0.4.0
    - docopt-ng==0.7.2